# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 898cf9e8b611de147e6434c76cfbad4ff17656a5eaf45ecc799ee4557eed923a19ace981f1f3e25e85391b6afc6ac8f5f2c1b161de977362827a86171dd86031

test:
  secret_key_base: d51c335e0dbd0297bb74efb160d7a65ade59fde87a204dabeafeb46f3bbe09de842ca8bc226d7f0d3c9239ff45cac69ac7aab8eb153ae8b8aba006c205196f93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
